### PR TITLE
ForcedVideoCodec default set to MEDIA_SERVER_PREFERRED

### PR DESCRIPTION
**Pull request by j1elo**
**`MEDIA_SERVER_PREFERRED`**: A recommended choice is done for you, based on the media server that is currently in use. This is the default setting, and is equivalent to these values:

    - For *mediasoup*, `NONE` is selected.
    - For *Kurento*, `VP8` is selected.

**Status**:

- [x] Added `MEDIA_SERVER_PREFERRED` as a selectable choice in the ForcedViceoCodec enums.
- [x] Added `forcedVideoCodecResolved` field to the SessionProperties class (which gets sent back and forth between server and clients during Session initialization).
    - [x] OpenVidu Server
    - [x] Java client
    - [x] Node client

- [ ] Run, review, and fix failing tests, if any.
    - [x] Fix

        > Error in number of keys in JSON object. Expected 12. Actual: 13.

        in [OpenViduTestAppE2eTest.java:2931](https://github.com/OpenVidu/openvidu/blob/747026134570da2ba21de1e8af2295afd7ae2f82/openvidu-test-e2e/src/test/java/io/openvidu/test/e2e/OpenViduTestAppE2eTest.java#L2931).
        The REST session properties now have one more value than before (`forcedVideoCodecResolved`), so this error makes sense, it just needs updating the test.

        **Fixed**. The new JSON key (`forcedVideoCodecResolved`) has been added in appropriate places.

    - [x] Fix

        > expected:<video/[MEDIA_SERVER_PREFERRED]> but was:<video/[VP8]>

        in [OpenViduTestAppE2eTest.java:4502](https://github.com/OpenVidu/openvidu/blob/747026134570da2ba21de1e8af2295afd7ae2f82/openvidu-test-e2e/src/test/java/io/openvidu/test/e2e/OpenViduTestAppE2eTest.java#L4502).
        @cruizba mentioned that this test is fetching the currently used codec directly from WebRTC Stats, and comparing it with the selected string in the TestApp. This broke because previously, the selected string would be `"VP8"`, which coincides with the name of the codec in WebRTC stats; but now it is `"MEDIA_SERVER_PREFERRED"`.
        Extra observations:
        - This test would have also failed previously with the `"NONE"` string, for the same reason; so this is not a breakage introduced by the changes in this PR, but an issue that already existed before (but was hidden just by luck).
        - This method assumes that the enum names in our source code match the names in WebRTC Stats, which so far has been the case (again by chance), but it is a very brittle assumption and won't fly too far. For example our enums will one day include `AV1`, however the name in Chrome is `AV1X` (and other browsers might name it differently? Not sure).

        **Fixed**. `MEDIA_SERVER_PREFERRED` and `NONE` have been special-cased to translate them into `VP8`. This is a **Kurento & Chrome -specific fix**, given that the test was only running with Kurento as media server, and Chrome as web browser, and we know that both have `VP8` as their preferred codec. A whole rethinking will be needed if we want this test running with mediasoup.

    - [ ] Fix failing test for Edge browser (see builds [5831](https://ci.openvidu.io/jenkins/job/Build/job/openvidu-server-e2e/5831/), [5832](https://ci.openvidu.io/jenkins/job/Build/job/openvidu-server-e2e/5832/)):

        > [ERROR] Tests run: 50, Failures: 0, Errors: 1, Skipped: 20, Time elapsed: 1,259.24 s <<< FAILURE! - in io.openvidu.test.e2e.OpenViduTestAppE2eTest
        > [ERROR] io.openvidu.test.e2e.OpenViduTestAppE2eTest.crossBrowserTest  Time elapsed: 311.623 s  <<< ERROR!
        > java.lang.Exception:
        > org.openqa.selenium.SessionNotCreatedException: Could not start a new session. New session request timed out
        > [...]
        > at io.openvidu.test.e2e.OpenViduTestAppE2eTest.lambda$crossBrowserTest$10([OpenViduTestAppE2eTest.java:464](https://github.com/OpenVidu/openvidu/blob/4c6e388cabec87caf90aaa05e303445a72317953/openvidu-test-e2e/src/test/java/io/openvidu/test/e2e/OpenViduTestAppE2eTest.java#L464))

- [ ] Run, review, and fix failing tests, if any (OpenVidu PRO).

### CODE REVIEW

**Comment by cruizba** [comment]
I've tested `openvidu-node-client` and `openvidu-java-client` and everything seems to work well.

The unique thing I would try to change is to hide these attribute to OpenVidu developers: 
- https://github.com/OpenVidu/openvidu/blob/63ea6c7ef0/openvidu-java-client/src/main/java/io/openvidu/java/client/SessionProperties.java#L252
- https://github.com/OpenVidu/openvidu/blob/63ea6c7ef0/openvidu-node-client/src/SessionProperties.ts#L92

As far as I understood, `forcedVideoCodecResolved` is the default value coming from the server, and the used one when no `forcedCodec` is defined in the `SessionProperties` object. I don't know how it would behave if a developer modifies this attribute, but I would try to mark it as deprecated in favor of `forcedCodec` or hide this attribute.

PS: To check force codecs, I've used the webrtc-internal tab of Chrome, and it seems like the codec attribute appears again :). Here is the VP9 codec:
image

I will test tomorrow with Firefox and disabling VP8, to see if transcoding still working in Kurento Media Server

I add these three TODO's which:
[ ] Forbid run OpenVidu server when media server is mediasoup and `OPENVIDU_STREAMS_ALLOW_TRANSCODING=true`
[ ] Allow Transcoding Test with KMS
[ ] Maybe hide  `forcedVideoCodecResolved` (?) I need feedback on that.

**Comment by cruizba** [comment]
@micaelgallego @pabloFuente I am agree that we can ignore. On the other hand, I had put this logic in there on OpenVidu CE because there is no other way to know in OpenViduConfig class what type of media server is being used. The media server type is discovered using a kurento-client method which is called after the OpenViduConfig class.

**Comment by cruizba** [comment]
@micaelgallego @pabloFuente @j1elo I've reverted the change of stop OpenVidu if `OPENVIDU_STREAMS_ALLOW_TRANSCODING=true`. 

I also see that this contemplated in the code:
https://github.com/OpenVidu/openvidu/blob/63ea6c7/openvidu-server/src/main/java/io/openvidu/server/kurento/core/KurentoSessionManager.java#L391-L393

I would consider the feature done from my tests.

**Comment by j1elo** [comment]
> The unique thing I would try to change is to hide these attribute to OpenVidu developers:
> 
>     * https://github.com/OpenVidu/openvidu/blob/63ea6c7ef0/openvidu-java-client/src/main/java/io/openvidu/java/client/SessionProperties.java#L252
> 
>     * https://github.com/OpenVidu/openvidu/blob/63ea6c7ef0/openvidu-node-client/src/SessionProperties.ts#L92
> 
> 
> As far as I understood, `forcedVideoCodecResolved` is the default value coming from the server, and the used one when no `forcedCodec` is defined in the `SessionProperties` object. I don't know how it would behave if a developer modifies this attribute, but I would try to mark it as deprecated in favor of `forcedCodec` or hide this attribute.

Done! (warning: force-pushed)

**Pull request merged**
