### PR TITLE
make getSessionId & generateToken error first callback

### PR DESCRIPTION
**Pull request by talentedandrew**
getSessionId & generateToken should follow nodejs' native error-first callback pattern. This makes it easy to catch errors.

### CODE REVIEW

**Comment by micaelgallego** [comment]
Thank you @talentedandrew for your PR. As this is a break of the current API, it is an important PR. 

We are thinking in use Promises in openvidu-node-client instead of callbacks. What do you think about it? Promises avoid callback hell and also can be used with async/await ES2017 features.

**Comment by talentedandrew** [comment]
@micaelgallego, I think using Promise would be a great idea.

**Comment by talentedandrew** [comment]
@micaelgallego , If you say I could create another PR replacing all the requests with Promises. What do you think about it?

**Comment by piranna** [comment]
+1000 about using Promises, I already proposed it but it was something too much confusing in that days yet, but code gets a lot cleaner once you understand them (and use them correctly too, obviously...).

**Comment by pabloFuente** [comment]
Refactoring all the callback based APIs to Promise based APIs is already planned in our roadmap. This breaking change will affect not only the node client (openvidu-node-client), but most importantly the browser client (openvidu-browser). A new major version of openvidu will be relased when this is implemented in the near future, and we will try to provide some documentation or tutorials on how to properly migrate previous code to the new version. Once a simple example is well understood it is really easy to adapt callbacks to promises.

**Comment by pabloFuente** [comment]
Promises are now used in both OpenVidu Browser and OpenVidu Node Client in release 2.0.0. Proceeding to close this PR.

**Pull request closed without merging**
