### PR TITLE
openvidu-server: add message sent event

### PR DESCRIPTION
**Pull request by brunobottazzini**
This patch registers the sendMessage event (signal: chat and signal: xxx) for tracking all the messages exchanged between the various clients.

As pointed out inside issues:
https://github.com/OpenVidu/openvidu/issues/288 and https://github.com/OpenVidu/openvidu/issues/399

### CODE REVIEW

**Comment by ruhulx** [comment]
@brunobottazzini , @cirinoe : 
Any progress on this pull request. Badly needed this feature. Thank you.
If necessary I'm ready to resolve the conflicts.

**Comment by brunobottazzini** [comment]
> @brunobottazzini , @cirinoe :
> Any progress on this pull request. Badly needed this feature. Thank you.
> If necessary I'm ready to resolve the conflicts.

Hello @ruhulx, I have updated the PR got a conflict but nothing serious. I hope that the maintainers start reviewing and merging it soon or at least to suggest some changes if needed.

**Comment by micaelgallego** [comment]
We are aware of this PR. We will take a look in the next few days

**Comment by banagale** [comment]
@micaelgallego Any chance this might be included in the next release?

**Comment by banagale** [comment]
I’m sure y’all have a lot to look at right now and I’m in great appreciation of the work on this project. 

I need this functionality, and may look at adding timestamps to the original signals also. 

I am hoping to attempt a custom build and deployment to get it next week. 

It would be good to know if there are plans for this specific implementation to be in the next release or not, though. 

Again, thanks for all of the work on this project.

**Comment by micaelgallego** [comment]
This PR is in our internal backlog...

We will take a look in the following weeks

**Comment by banagale** [comment]
@micaelgallego @pabloFuente 
Can this be pulled in for 2.16?

**Comment by pabloFuente** [comment]
In master branch a new event called `signalEvent` is now available for the Webhook and CDR (see commit e8dd9bd8f4c739a83f26d9d9f6b59393e17337eb). This PR has not been merged becasue some minor changes were required, but the functionality is the expected one. Will be officially available in 2.17.0.

**Pull request closed without merging**
