### PR TITLE
screen share bug fix.

### PR DESCRIPTION
**Pull request by willylee007**
1. modify screen share, request screen => initScreenPublisher => publish(screenPublisher)
2. detect screen share stopped by user

### CODE REVIEW

**Comment by pabloFuente** [comment]
Hi, thanks for the PR. I can tell that you have implemented an event to know if the user has stopped screen-sharing. But which is exactly the bug you stated in point 1?

Also, we are right now refactoring openvidu-browser in depth and cannot accept any pull requests. Release 2.0.0 will be released soon and the we can study this change.

Thanks!

**Comment by willylee007** [comment]
In point 1, testing with [testapp](https://github.com/OpenVidu/openvidu/tree/master/openvidu-testapp), when user change publisher from video to screen share, output was interrupted. So we should publish new publisher after user's agreement.

**Comment by pabloFuente** [comment]
This desired behaviour can be achieved just by using standard OpenVidu Browser API. For example, openvidu-testapp has been adapted to not unpublish the camera until screen-share stream is ready to be published. The exact method is this:
https://github.com/OpenVidu/openvidu/blob/5c4fac0f3273380fb23b4f3043b97aae10b8f374/openvidu-testapp/src/app/components/openvidu-instance/openvidu-instance.component.ts#L521-L590

You can test this scenario by running 

```
docker run -p 4443:4443 openvidu/testapp
```

Connect to `https://localhost:4443`, init a Publisher (with camera) and  a Subscriber and click on "Change publisher" icon in the Publisher's view. It will ask for a window to screen-share but keeping the camera until user selects one.

**Comment by pabloFuente** [comment]
We still have to study the "screen share stopped by user" feature

**Pull request closed without merging**
